### ISSUE TITLE
Endless loop with QGIS Auth password manager in a fresh profile

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#48]
After mergin plugin installation, when user tries to log into to Mergin, it keeps asking for QGIS master password 100s of times. Either QGIS password manager is broken or the way Mergin is using it....

It ends up freezing QGIS.

**Comment by saberraz** [comment]
The platform and plugin details:
Ubuntu 18.04
QGIS 3.8
Mergin plugin 2019.4-1

**Comment by waiotahi** [comment]
![image](https://user-images.githubusercontent.com/53323943/64906281-8e79d400-d738-11e9-967f-20c6a3442422.png)

I too have same issue / Windows 10 / QGIS 3.8  / yet I can test connection after entering username & pswd on the Mergin plugin settings page and it replies OK !

**Comment by saberraz** [comment]
@waiotahi the password to enter here is QGIS master password and not mergin.

Could you reset QGIS master password for mergin, by going to Settings > Options. In the new window, click in Authentication tab, and remove the row for mergin:
![image](https://user-images.githubusercontent.com/2649047/64906540-dae4f580-d6df-11e9-8a2c-5e7a7a30ca25.png)

Restart QGIS and try to configure the connection again.

**Comment by waiotahi** [comment]
Thanks for that - there was no row for Mergin but I went to Authentication/Utilities and reset the password - its now working !

**Comment by saberraz** [comment]
Another reported issue which was fixed with resetting the Auth entry:

> ‘Error. Invalid Token Type’.

**Comment by saberraz** [comment]
I think the main source of confusion is user unfamiliarity with QGIS Password Manager. Maybe we should follow PostGIS connection settings: big warning for saving it as plain text. And if opt to save the credential in QGIS password manager, prompt users to set the password for the wallet first.

**Comment by QuentinStrappazzon** [comment]
Hi,

I do have the same "Error Invalid token type" whereas my Mergin connexion details are correct
![image](https://user-images.githubusercontent.com/53568185/67500030-5db78380-f682-11e9-9e5e-993b56dbf64e.png)

Windows 10
QGIS 3.8.3
Mergin 2019-4-1

I followed your advices regarding the Auth password but it didn't solve the problem for me. 

When modifying Auth password I get a python error as well.

Any ideas how to fix this ?

Thks by advance

**Comment by saberraz** [comment]
Hi @QuentinStrappazzon 
the issue has been fixed in the master. We will release a new plugin later next week with this and more enhancements/bug fixes.

Thanks for your feedback and reporting the issue.
